### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by surereddy** [happyfire/SimpleTunnelServer#1]
Hello sir i tried to build it but i cannot make it with make i have the below error 
make
gcc -g -Wall -Werror -std=gnu99 -I/usr/include/libev  -c -o src/tunnel_server.o src/tunnel_server.c
src/tunnel_server.c: In function ‘socket_read’:
src/tunnel_server.c:128:9: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘ssize_t’ [-Werror=format=]
         LOGV(5, "receive udp data len: [%lu]", nread);
         ^
src/tunnel_server.c: In function ‘tun_read’:
src/tunnel_server.c:173:5: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t’ [-Werror=format=]
     LOGV(5, "read tun len: [%lu]", nread);
     ^
cc1: all warnings being treated as errors
make: *** [src/tunnel_server.o] Error 1

i'm trying to build on ubuntu 14.04 32 bit

**Comment by happyfire** [comment]
I thinks it maybe due to compiler version, you can remove -Werror. I build it in centos 6.9.

**Comment by surereddy** [comment]
Still error sir 

make
gcc -lev -o server src/main.o src/tunnel_server.o src/client.o src/utils.o src/server_ip.o src/server_connect.o src/server_transout.o src/server_transin.o
src/tunnel_server.o: In function `tunnel_server_start':
/root/SimpleTunnelServer/src/tunnel_server.c:290: undefined reference to `ev_default_loop'
/root/SimpleTunnelServer/src/tunnel_server.c:306: undefined reference to `ev_io_start'
/root/SimpleTunnelServer/src/tunnel_server.c:309: undefined reference to `ev_run'
src/server_connect.o: In function `server_on_connect':
/root/SimpleTunnelServer/src/server_connect.c:46: undefined reference to `ev_time'
/root/SimpleTunnelServer/src/server_connect.c:48: undefined reference to `ev_timer_stop'
src/server_connect.o: In function `timeout_cb':
/root/SimpleTunnelServer/src/server_connect.c:81: undefined reference to `ev_timer_stop'
/root/SimpleTunnelServer/src/server_connect.c:83: undefined reference to `ev_timer_start'
src/server_connect.o: In function `send_connect_ok':
/root/SimpleTunnelServer/src/server_connect.c:107: undefined reference to `ev_timer_start'
src/server_transout.o: In function `server_on_transout':
/root/SimpleTunnelServer/src/server_transout.c:71: undefined reference to `ev_io_start'
/root/SimpleTunnelServer/src/server_transout.c:77: undefined reference to `ev_time'
/root/SimpleTunnelServer/src/server_transout.c:81: undefined reference to `ev_timer_stop'
/root/SimpleTunnelServer/src/server_transout.c:83: undefined reference to `ev_timer_start'
collect2: error: ld returned 1 exit status
make: *** [server] Error 1

**Comment by happyfire** [comment]
Do you have libev installed?

**Comment by surereddy** [comment]
apt-get install libev-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libev-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
